name: Build APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install buildozer
          sudo apt-get update
          sudo apt-get install -y libtool-bin autoconf libltdl-dev libffi-dev libssl-dev openjdk-17-jdk
      - name: Build APK
        run: buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: liveauth-debug
          path: bin/*.apk
